#!/bin/bash
mkdir -p /var/log/nginx
chown -R www-data:www-data /var/log/nginx
chmod -R 644 /var/log/nginx
chmod 755 /var/log/nginx
touch /var/log/syslog   && chown -f root:adm /var/log/syslog*
touch /var/log/auth.log && chown -f root:adm /var/log/auth.log*
touch /var/log/kern.log && chown -f root:adm /var/log/kern.log*
