#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/standalone
$DIR/two-container
$DIR/update-old-templates

if [ -f $DIR/../containers/app.yml ] || [ -f $DIR/../containers/web_only.yml ]
then
  echo Some test failed. Sad.
fi
