#!/bin/bash
set -e
PNGCRUSH_VERSION=1.7.92
cd /tmp
wget http://iweb.dl.sourceforge.net/project/pmt/pngcrush/$PNGCRUSH_VERSION/pngcrush-$PNGCRUSH_VERSION.tar.gz
tar zxf pngcrush-$PNGCRUSH_VERSION.tar.gz
cd pngcrush-$PNGCRUSH_VERSION
make && cp -f pngcrush /usr/local/bin
cd /
rm -fr /tmp/pngcrush-$PNGCRUSH_VERSION
rm /tmp/pngcrush-$PNGCRUSH_VERSION.tar.gz
