#!/bin/bash
set -e

# version check: https://www.lcdf.org/gifsicle/
VERSION=1.92
HASH="5ab556c01d65fddf980749e3ccf50b7fd40de738b6df679999294cc5fabfce65"

cd /tmp
curl -O http://www.lcdf.org/gifsicle/gifsicle-$VERSION.tar.gz
sha256sum gifsicle-$VERSION.tar.gz
echo "$HASH gifsicle-$VERSION.tar.gz" | sha256sum -c

tar zxf gifsicle-$VERSION.tar.gz
cd gifsicle-$VERSION
./configure
make install
cd /
rm -fr /tmp/gifsicle*
