#!/bin/bash
set -e
PNGCRUSH_VERSION=1.8.13
cd /tmp
wget https://sourceforge.net/projects/pmt/files/pngcrush/$PNGCRUSH_VERSION/pngcrush-$PNGCRUSH_VERSION.tar.gz/download -O pngcrush-$PNGCRUSH_VERSION.tar.gz
tar zxf pngcrush-$PNGCRUSH_VERSION.tar.gz
cd pngcrush-$PNGCRUSH_VERSION
make && cp -f pngcrush /usr/local/bin
cd /
rm -fr /tmp/pngcrush-$PNGCRUSH_VERSION
rm /tmp/pngcrush-$PNGCRUSH_VERSION.tar.gz
