#!/bin/bash
set -e

RUBY_VERSION="3.2.1"
export CONFIGURE_OPTS="--enable-yjit"
export DEBIAN_FRONTEND=noninteractive

apt-get -y --no-install-recommends install ruby bison libffi-dev

mkdir /src
git -C /src clone https://github.com/rbenv/ruby-build.git
cd /src/ruby-build && ./install.sh
cd / && rm -fr /src

ruby-build ${RUBY_VERSION} /usr/local

apt-get -y purge ruby
