#!/bin/bash
set -e

VIPS_VERSION="8.18.4"
VIPS_HASH="2677bad6c422617fd1172d359c16af34e736965d042c214203a87187d26ff037"
WDIR=/tmp/vips
PACKAGE_DIR=/tmp/vips-packages

export DEBIAN_FRONTEND=noninteractive
apt-get -y -q install --no-install-recommends devscripts equivs
apt-get -y -q install /tmp/jpegli-debs/discourse-libjpegli62_*.deb /tmp/jpegli-debs/discourse-libjpegli-dev_*.deb

mkdir -p "$WDIR" "$PACKAGE_DIR"
wget -q -O /tmp/vips.tar.xz "https://github.com/libvips/libvips/releases/download/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.xz"
echo "$VIPS_HASH  /tmp/vips.tar.xz" | sha256sum -c
tar xf /tmp/vips.tar.xz --strip-components=1 -C "$WDIR"
cp -a /tmp/vips-packaging/debian "$WDIR/debian"

cd "$WDIR"
mk-build-deps --install --remove \
  --tool 'apt-get -y -q --no-install-recommends' \
  debian/control
DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" dpkg-buildpackage -us -uc -b
cp ../discourse-libvips42_*.deb ../discourse-vips-tools_*.deb "$PACKAGE_DIR/"
