#!/bin/bash
set -e

LIBHEIF_VERSION="1.23.1"
DEBIAN_VERSION="$LIBHEIF_VERSION-1"
BASE_URL="https://deb.debian.org/debian/pool/main/libh/libheif"
WDIR=/tmp/libheif
PACKAGE_DIR=/tmp/libheif-packages

DSC="libheif_${DEBIAN_VERSION}.dsc"
ORIG="libheif_${LIBHEIF_VERSION}.orig.tar.gz"
DEBIAN_TAR="libheif_${DEBIAN_VERSION}.debian.tar.xz"

export DEBIAN_FRONTEND=noninteractive
apt-get -y -q install devscripts equivs

mkdir -p "$WDIR" "$PACKAGE_DIR"
cd "$WDIR"

wget -q "$BASE_URL/$DSC" "$BASE_URL/$ORIG" "$BASE_URL/$DEBIAN_TAR"
cat <<EOF | sha256sum -c
a9c2ea49af68fb13ac57b167cef3325c655fbe66a6f6eba16c1acb6c262d1b25  $DSC
0de0327f60fcd47de90d5654c6fe152232738d60d84fe084ec3e0f35e03b166a  $ORIG
e237289f23bc6607681843de81e9c19429ea5f1ca0f87b880658d08065179181  $DEBIAN_TAR
EOF

dpkg-source -x "$DSC"
cd "libheif-$LIBHEIF_VERSION"
DEBFULLNAME="Discourse Team" DEBEMAIL="team@discourse.org" \
  dch --force-bad-version --newversion "$LIBHEIF_VERSION-1~bpo13+discourse1" \
      --distribution trixie --force-distribution \
      "Rebuild Debian libheif 1.23.1 for the Discourse Trixie image."
mk-build-deps --install --remove \
  --tool 'apt-get -y -q --no-install-recommends' \
  debian/control
DEB_BUILD_OPTIONS="parallel=$(nproc)" dpkg-buildpackage -us -uc -b

cp ../libheif1_*.deb \
   ../libheif-dev_*.deb \
   ../libheif-plugin-aomdec_*.deb \
   ../libheif-plugin-aomenc_*.deb \
   ../libheif-plugin-libde265_*.deb \
   ../libheif-plugin-x265_*.deb \
   "$PACKAGE_DIR/"

apt-get -y -q install \
  "$PACKAGE_DIR"/libheif1_*.deb \
  "$PACKAGE_DIR"/libheif-dev_*.deb \
  "$PACKAGE_DIR"/libheif-plugin-aomdec_*.deb \
  "$PACKAGE_DIR"/libheif-plugin-aomenc_*.deb \
  "$PACKAGE_DIR"/libheif-plugin-libde265_*.deb \
  "$PACKAGE_DIR"/libheif-plugin-x265_*.deb
ldconfig

test "$(pkg-config --modversion libheif)" = "$LIBHEIF_VERSION"
test "$(find /usr/lib -path '*/libheif/plugins/libheif-aomdec.so' | wc -l)" -eq 1
test "$(find /usr/lib -path '*/libheif/plugins/libheif-aomenc.so' | wc -l)" -eq 1
test "$(find /usr/lib -path '*/libheif/plugins/libheif-libde265.so' | wc -l)" -eq 1
test "$(find /usr/lib -path '*/libheif/plugins/libheif-x265.so' | wc -l)" -eq 1
