#!/bin/bash
set -e

# version check: https://nginx.org/en/download.html
NGINX_VERSION=1.23.3
NGINX_HASH="75cb5787dbb9fae18b14810f91cc4343f64ce4c24e27302136fb52498042ba54"
NGINX_TEMP_DIR=/var/lib/nginx
NGINX_LOG_DIR=/var/log/nginx

export DEBIAN_FRONTEND=noninteractive

cd /tmp
wget -q https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
sha256sum nginx-$NGINX_VERSION.tar.gz
echo "$NGINX_HASH nginx-$NGINX_VERSION.tar.gz" | sha256sum -c
tar -zxf nginx-$NGINX_VERSION.tar.gz
cd nginx-$NGINX_VERSION

# nginx-common for boilerplate files etc.
apt-get -y install nginx-common

cd /tmp
# this is the reason we are compiling by hand...
git clone https://github.com/google/ngx_brotli.git
# now ngx_brotli has brotli as a submodule
cd /tmp/ngx_brotli
git submodule update --init

cd /tmp/nginx-$NGINX_VERSION
# ignoring depracations with -Wno-deprecated-declarations while we wait for this https://github.com/google/ngx_brotli/issues/39#issuecomment-254093378
./configure --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' \
    --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' \
    --prefix=/usr/share/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --http-log-path=${NGINX_LOG_DIR}/access.log \
    --error-log-path=${NGINX_LOG_DIR}/error.log \
    --lock-path=/var/lock/nginx.lock \
    --pid-path=/run/nginx.pid \
    --http-client-body-temp-path=${NGINX_TEMP_DIR}/body \
    --http-fastcgi-temp-path=${NGINX_TEMP_DIR}/fastcgi \
    --http-proxy-temp-path=${NGINX_TEMP_DIR}/proxy \
    --http-scgi-temp-path=${NGINX_TEMP_DIR}/scgi \
    --http-uwsgi-temp-path=${NGINX_TEMP_DIR}/uwsgi \
    --with-debug \
    --with-pcre-jit \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_auth_request_module \
    --with-http_addition_module \
    --with-http_dav_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_v2_module \
    --with-http_sub_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-threads \
    --add-module=/tmp/ngx_brotli

make install

mv /usr/share/nginx/sbin/nginx /usr/sbin

cd /
rm -fr /tmp/nginx
rm -fr /tmp/libbrotli
rm -fr /tmp/ngx_brotli
rm -fr /etc/nginx/modules-enabled/*
