#!/bin/bash
set -e

# version check: https://github.com/shssoichiro/oxipng/releases
OXIPNG_VERSION="7.0.0"
OXIPNG_FILE="oxipng-${OXIPNG_VERSION}-x86_64-unknown-linux-musl.tar.gz"
OXIPNG_HASH="f794df937abcc2ef9357dcc52c39908f390461921fcbd19793f35d33120bfc8e"

# Install other deps
apt -y -q install advancecomp jhead jpegoptim libjpeg-turbo-progs optipng

if [ $(dpkg --print-architecture) != "amd64" ]; then
  cargo install oxipng@${OXIPNG_VERSION}
  rm -rf /usr/local/cargo/registry
  
  exit 0
fi

mkdir /oxipng-install
cd /oxipng-install

wget -q https://github.com/shssoichiro/oxipng/releases/download/v${OXIPNG_VERSION}/${OXIPNG_FILE}
sha256sum ${OXIPNG_FILE}
echo "${OXIPNG_HASH} ${OXIPNG_FILE}" | sha256sum -c

tar --strip-components=1 -xzf $OXIPNG_FILE
cp -v ./oxipng /usr/local/bin
cd / && rm -fr /oxipng-install
