#!/bin/bash
set -e

JEMALLOC_VERSION="3.6.0"
JEMALLOC_HASH="e16c2159dd3c81ca2dc3b5c9ef0d43e1f2f45b04548f42db12e7c12d7bdf84fe"
WDIR=/tmp/discourse-jemalloc-$JEMALLOC_VERSION
PACKAGE_DIR=/tmp/jemalloc-packages

export DEBIAN_FRONTEND=noninteractive
apt-get -y -q install debhelper

mkdir -p "$WDIR" "$PACKAGE_DIR"
wget -q -O /tmp/jemalloc.tar.bz2 \
  "https://github.com/jemalloc/jemalloc/releases/download/$JEMALLOC_VERSION/jemalloc-$JEMALLOC_VERSION.tar.bz2"
echo "$JEMALLOC_HASH  /tmp/jemalloc.tar.bz2" | sha256sum -c
tar --strip-components=1 -xjf /tmp/jemalloc.tar.bz2 -C "$WDIR"
cp -a /tmp/jemalloc-packaging/debian "$WDIR/debian"

cd "$WDIR"
DEB_BUILD_OPTIONS="parallel=$(nproc)" dpkg-buildpackage -us -uc -b
cp ../libjemalloc1_*.deb "$PACKAGE_DIR/"
apt-get -y -q install "$PACKAGE_DIR"/libjemalloc1_*.deb
dpkg-deb --info "$PACKAGE_DIR"/libjemalloc1_*.deb >/dev/null
LD_PRELOAD=/usr/lib/libjemalloc.so.1 ruby -e '100_000.times { Object.new }; GC.start'
