#!/bin/bash
set -e

JPEGLI_COMMIT="031a0077f5799a6041004267fc12b956c1f52a20"
JPEGLI_HASH="269b3a75d6b2da2351f7fb2d642043f60f9b6d1bd5839f20c0d7c569be073367"
WDIR=/tmp/jpegli
PACKAGE_DIR=/tmp/jpegli-packages

export DEBIAN_FRONTEND=noninteractive
apt-get -y -q install --no-install-recommends devscripts equivs

mkdir -p "$WDIR" "$PACKAGE_DIR"
wget -q -O /tmp/jpegli.tar.gz "https://github.com/google/jpegli/archive/$JPEGLI_COMMIT.tar.gz"
echo "$JPEGLI_HASH  /tmp/jpegli.tar.gz" | sha256sum -c
tar xf /tmp/jpegli.tar.gz --strip-components=1 -C "$WDIR"
rm -rf "$WDIR/debian"
cp -a /tmp/jpegli-packaging/debian "$WDIR/debian"

cd "$WDIR"
mk-build-deps --install --remove \
  --tool 'apt-get -y -q --no-install-recommends' \
  debian/control

MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
mkdir -p third_party/libjpeg-turbo
cp /usr/include/jpeglib.h third_party/libjpeg-turbo/jpeglib.h
cp /usr/include/jmorecfg.h third_party/libjpeg-turbo/jmorecfg.h
cp "/usr/include/$MULTIARCH/jconfig.h" third_party/libjpeg-turbo/jconfig.h.in

DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" dpkg-buildpackage -us -uc -b
cp ../discourse-libjpegli62_*.deb ../discourse-libjpegli-dev_*.deb "$PACKAGE_DIR/"
