#!/bin/bash
set -e

RUBY_VERSION="3.2.0"
export CONFIGURE_OPTS="--enable-yjit"

apt-get -y install --no-install-recommends ruby bison

mkdir /src
git -C /src clone https://github.com/rbenv/ruby-build.git
cd /src/ruby-build && ./install.sh
cd / && rm -fr /src

ruby-build ${RUBY_VERSION} /usr/local

apt-get -y purge ruby
