#!/bin/sh
set -e

RUNDIR=/var/run/redis
PIDFILE=/var/run/redis/redis-server.pid

mkdir -p $RUNDIR
touch $PIDFILE
chown -R redis:redis $RUNDIR
chmod 755 $RUNDIR

exec chpst -u redis /usr/bin/redis-server /etc/redis/redis.conf
