#!/bin/bash

docker build -t discourse/dev:1.0.13 .
docker save discourse/dev:1.0.13 | ../docker-squash -t discourse/dev:1.0.13 -verbose -from root | docker load
docker tag -f discourse/dev:1.0.13 discourse/dev:latest

