#!/bin/bash
set -e

# The Selenium gem isn’t shipped with the `selenium-manager` binary for aarch64
# either (yet). So we have to compile it ourselves.
if [ "$(dpkg --print-architecture)" = "arm64" ]; then
    cd /tmp
    /tmp/install-rust
    git clone --depth 1 --no-checkout https://github.com/SeleniumHQ/selenium.git
    cd selenium
    git sparse-checkout set rust
    git checkout
    cd rust
    cargo build --release
    cp target/release/selenium-manager /usr/local/bin
    rustup self uninstall -y
    cd /
    rm -rf /tmp/*
fi