on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: build-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

env:
  BUILDKIT_PROGRESS: plain
  BASE_REPO: ${{ vars.BASE_REPO }}
  TEST_REPO: ${{ vars.TEST_REPO }}
  DEV_REPO: ${{ vars.DEV_REPO }}
  SETUP_WIZARD_REPO: ${{ vars.SETUP_WIZARD_REPO }}

jobs:
  timestamp:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)) }}
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - id: timestamp
        run: |
          timestamp=`date +%Y%m%d-%H%M`
          echo "timestamp=$timestamp"
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT

  base:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)) }}
    # `cdck-linux-8-core` for amd64 builds
    # `ubuntu-24.04-8core-arm` for arm64 builds
    runs-on: ${{ (matrix.arch == 'amd64' && vars.AMD64_RUNNER) || vars.ARM64_RUNNER }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    timeout-minutes: 90
    needs: timestamp
    defaults:
      run:
        working-directory: image
    env:
      TIMESTAMP: ${{ needs.timestamp.outputs.timestamp }}
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build runtime deps
        run: |
          docker buildx bake base-runtime-deps --no-cache --load

      - name: Build slim image
        run: |
          docker buildx bake base-slim --load

      - name: Build web only image
        run: |
          docker buildx bake base-web-only --load

      - name: Build release image
        run: |
          docker buildx bake base-release --load

      - name: Build test image
        run: |
          docker buildx bake base-test --load

      - name: run specs for `main` branch
        if: vars.SKIP_TESTS != '1'
        run: |
          docker run --rm -e RUBY_ONLY=1 -e USE_TURBO=1 -e SKIP_PLUGINS=1 -e SKIP_LINT=1 -e DISCOURSE_TURBO_RSPEC_RETRY_AND_LOG_FLAKY_TESTS=1 ${TEST_REPO}:build-${{ matrix.arch }}

      - name: Build and push dev image
        run: |
          docker buildx bake dev --push --allow=fs.read=../templates

      - name: Print summary
        run: |
          docker images ${BASE_REPO}

      - name: Print `docker history` summary for main branch image
        run: |
          docker history ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-${{ matrix.arch }}

      - name: push to dockerhub
        if: github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)
        run: |
          docker buildx bake base-push-tags --push

      - name: Push discourse_base:aarch64 image for backwards compatibility
        if: (github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)) && (matrix.arch == 'arm64')
        run: |
          docker tag ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-${{ matrix.arch }} ${BASE_REPO}:aarch64
          docker push ${BASE_REPO}:aarch64

  setup_wizard:
    if: github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)
    runs-on: ${{ (matrix.arch == 'amd64' && vars.AMD64_RUNNER) || vars.ARM64_RUNNER }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    defaults:
      run:
        working-directory: image
    env:
      ARCH: ${{ matrix.arch }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push to dockerhub
        run: |
          docker buildx bake setup-wizard --push

  push_multi_arch_manifests:
    runs-on: ubuntu-latest
    needs: [base, setup_wizard, timestamp]
    env:
      TIMESTAMP: ${{ needs.timestamp.outputs.timestamp }}
    if: github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: create and push multi-arch manifests
        run: |
          # Slim timestamped
          docker buildx imagetools create -t ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-slim \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-slim-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-slim-main-arm64

          # Slim release
          docker buildx imagetools create -t ${BASE_REPO}:slim \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-slim-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-slim-main-arm64

          # Web-Only `main` timestamped
          docker buildx imagetools create -t ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-main-arm64

          # Web-Only `main` release
          docker buildx imagetools create -t ${BASE_REPO}:web-only \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-main-arm64

          # Web-Only `esr` timestamped
          docker buildx imagetools create -t ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-esr \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-esr-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-esr-arm64

          # Web-Only `esr` release
          docker buildx imagetools create -t ${BASE_REPO}:web-only-esr \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-esr-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-web-only-esr-arm64

          # Full Discourse `main` branch timestamped
          docker buildx imagetools create -t ${BASE_REPO}:2.0.${{ env.TIMESTAMP }} \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-arm64

          # Full Discourse `esr` branch timestamped
          docker buildx imagetools create -t ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-esr \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-esr-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-esr-arm64

          # Full Discourse `main` branch release
          docker buildx imagetools create -t ${BASE_REPO}:release \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-main-arm64

          # Full Discourse `esr` branch release
          docker buildx imagetools create -t ${BASE_REPO}:release-esr \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-esr-amd64 \
            ${BASE_REPO}:2.0.${{ env.TIMESTAMP }}-esr-arm64

          # Dev timestamped
          docker buildx imagetools create -t ${DEV_REPO}:${{ env.TIMESTAMP }} \
            ${DEV_REPO}:${{ env.TIMESTAMP }}-amd64 \
            ${DEV_REPO}:${{ env.TIMESTAMP }}-arm64

          # Dev release
          docker buildx imagetools create -t ${DEV_REPO}:release \
            ${DEV_REPO}:${{ env.TIMESTAMP }}-amd64 \
            ${DEV_REPO}:${{ env.TIMESTAMP }}-arm64

          # Setup wizard release
          docker buildx imagetools create -t ${SETUP_WIZARD_REPO}:release \
            ${SETUP_WIZARD_REPO}:release-amd64 \
            ${SETUP_WIZARD_REPO}:release-arm64

  test:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH)) }}
    runs-on: ${{ vars.AMD64_RUNNER }}
    timeout-minutes: 60
    needs: base
    defaults:
      run:
        working-directory: image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build discourse_test:*
        run: |
          docker buildx bake test --load
      - name: Print summary
        run: |
          docker images ${TEST_REPO}
      - name: Login to Docker Hub
        if: success() && (github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH))
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: push to dockerhub
        if: success() && (github.ref == format('refs/heads/{0}', vars.IMAGE_PUSH_BRANCH))
        run: |
          docker buildx bake test --push
