on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  BUILDKIT_PROGRESS: plain
  DOCKER_IMAGE: ${{ vars.WEB_ONLY_IMAGE }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.latest.outputs.version }}
      esr: ${{ steps.esr.outputs.version }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: checkout tests passed
        uses: actions/checkout@v4
        with:
          repository: discourse/discourse
          ref: latest
          fetch-depth: 1
          path: 'latest'
      - name: checkout esr
        uses: actions/checkout@v4
        with:
          repository: discourse/discourse
          ref: esr
          fetch-depth: 1
          path: 'esr'
      - id: latest
        working-directory: latest
        run: |
          version=$(ruby -r ./lib/version.rb -e "puts ::Discourse::VERSION::STRING")
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - id: esr
        working-directory: esr
        run: |
          version=$(ruby -r ./lib/version.rb -e "puts ::Discourse::VERSION::STRING")
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

  push:
    strategy:
      matrix:
        version: [latest,esr]
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    needs: version
    env:
      ARCH: ${{ matrix.os == 'ubuntu-24.04-arm' && 'arm64' || 'amd64' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: download-launcher
        run: |
          BINDIR="bin"
          package="${BINDIR}/launcher.tar.gz"
          curl -s -o ${package} -L https://get.discourse.org/launcher/latest/launcher-linux-${{ env.ARCH }}.tar.gz
          tar -zxf ${package} -C ${BINDIR}
          rm ${package}
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build
        run: |
          # TODO: can we find a way to override or provide pups params at build time?
          # Then we can do something like:
          # bin/launcher build --params="version=esr" --conf-dir=./samples web_only
          cp ./samples/web_only.yml ./containers/web_only.yml
          echo $(grep base_image: ./templates/web.template.yml)-web-only >> ./containers/web_only.yml
          sed -Ei 's/^ *+#?version:.*/  version: ${{ matrix.version }}/' ./containers/web_only.yml
          sed -Ei '/^env:.*/a\  DISABLE_LETSENCRYPT: 1' ./containers/web_only.yml
          sed -Ei '/^ *+- "templates\/web.template.yml"/a\  - "templates/offline-page.template.yml"' ./containers/web_only.yml
          sed -Ei 's/^ *+#- "templates\/web.ssl.template.yml"/  - "templates\/web.ssl.template.yml"/' ./containers/web_only.yml
          sed -Ei 's/^ *+#- "templates\/web.letsencrypt.ssl.template.yml"/  - "templates\/web.letsencrypt.ssl.template.yml"/' ./containers/web_only.yml
          bin/launcher build web_only \
            --tag ${{ env.DOCKER_IMAGE }} \
            --output=type=registry,push-by-digest=true \
            --metadata-file=/tmp/out.json
      - name: save image digests
        id: metadata
        run: |
          ${{ matrix.version }}_${{ env.ARCH }}=$(jq -r '."containerimage.digest"' /tmp/out.json)
          echo "${{ matrix.version }}_${{ env.ARCH }}=$${{ matrix.version }}_${{ env.ARCH }}"
          echo "${{ matrix.version }}_${{ env.ARCH }}=$${{ matrix.version }}_${{ env.ARCH }}" >> $GITHUB_OUTPUT
    outputs:
      latest_amd64: ${{ steps.metadata.outputs.latest_amd64 }}
      latest_arm64: ${{ steps.metadata.outputs.latest_arm64 }}
      esr_amd64: ${{ steps.metadata.outputs.esr_amd64 }}
      esr_arm64: ${{ steps.metadata.outputs.esr_arm64 }}

  manifest:
    runs-on: ubuntu-latest
    needs: [version, push]
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: update manifest
        run: |
          docker buildx imagetools create -t ${{ env.DOCKER_IMAGE }}:latest \
            ${{ needs.push.outputs.latest_amd64 }} \
            ${{ needs.push.outputs.latest_arm64 }}

          docker buildx imagetools create -t ${{ env.DOCKER_IMAGE }}:esr \
            ${{ needs.push.outputs.esr_amd64 }} \
            ${{ needs.push.outputs.esr_arm64 }}

          docker buildx imagetools create -t ${{ env.DOCKER_IMAGE }}:${{ needs.version.outputs.latest }} \
            ${{ needs.push.outputs.latest_amd64 }} \
            ${{ needs.push.outputs.latest_arm64 }}

          docker buildx imagetools create -t ${{ env.DOCKER_IMAGE }}:${{ needs.version.outputs.esr }} \
            ${{ needs.push.outputs.esr_amd64 }} \
            ${{ needs.push.outputs.esr_arm64 }}
